language: c

before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq make gcc-arm-none-eabi qemu-user

script: make -f Makefile.gcc clean && make -f Makefile.gcc check && qemu-arm -cpu cortex-a9 compute_ref.gccarm && diff  stm-arm-neon.gccarm ref-rvct-neon-nofp16.txt
